site_name: Soap CLI
site_description: "Command-line SOAP client"
site_url: https://marcemv90.github.io/SoapCLI
repo_url: https://github.com/marcemv90/SoapCLI
repo_name: marcemv90/SoapCLI

nav:
  - Home: index.md
  - Installation: installation-from-source.md
  - FAQ: faq.md
  - TO-DO: todo.md
  - CLI:
    - Overview: cli-overview.md
    - Basic usage: cli-basic-usage.md
    - Attachments: cli-attachments.md
    - Placeholders: cli-placeholders.md
    - Authentication: cli-auth.md
    - Profiles: cli-profiles.md
    - Proxy: cli-proxy.md
    - Themes: cli-themes.md
    - Return codes & errors: cli-rc-and-errors.md
    - Debug: cli-debug.md
  - Buy me a coffee: buy-me-a-coffee.md

theme:
  name: material
  language: en
  highlightjs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_style: dracula
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/styles/overrides.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/shell.min.js

docs_dir: docs
site_dir: site
